trigger:
  - master

pool:
  name: AKS Agents

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: CmdLine@2
  inputs:
    script: |
      az login --service-principal -u $(SP ID) -p $(SP Pwd) --tenant $(Tenant ID)
      az acr build --image sample-js:v1 --registry azdoselfhostedagentacr --file Dockerfile .
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile