trigger:
  - main

pool:
  name: AKS Agents

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: CmdLine@2
  inputs:
    script: 'az login --service-principal -u $(SP ID) -p $(SP Pwd) --tenant $(Tenant ID)'
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile