trigger:
  - master

pool:
  name: Private AKS Agents

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: CmdLine@2
  inputs:
    script: |
      go version
      img version

      # az login --service-principal -u $(Private SP ID) -p $(Private SP Pwd) --tenant $(Tenant ID)
      # az acr build --image sample-js:$(Build.BuildId) ./app --registry $(acrRegistryName) --file ./app/Dockerfile


# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile